name: Scrimmage3
authors: [msalihov, Jake0oo0, TheAtro, RainoBoy97]
description: Scrimmage plugin created for Overcast Network scrimmaging
version: ${project.version}
website: http://ocnscrim.github.io/
